nodeLinker: node-modules

packageExtensions:
  storybook@*:
    dependencies:
      "@storybook/addon-a11y": ^10.4.3
      "@storybook/addon-docs": ^10.4.3
      "@storybook/addon-mcp": ^0.6.0
      "@storybook/addon-vitest": ^10.4.3
      "@storybook/react-vite": ^10.4.3
