name: PR title lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install commitlint
        run: |
          npm init -y
          npm install --no-audit --no-fund @commitlint/cli @commitlint/config-conventional
      - name: Lint PR title
        run: |
          echo "${{ github.event.pull_request.title }}" > pr_title
          npx commitlint --config commitlint.config.js --edit pr_title
